version: '3.7'

services:
  portfolio:
    container_name: portfolio
    build: .
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.rule=Host(`shaamallow.com`)"

networks:
  web:
    external: true
